version: '3.8'

services:
  app:
    build: .
    container_name: python-server
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres:13.1
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - 5050:80
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379

  celery_worker:
    image: fastapi_celery_example_celery_worker
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    image: fastapi_celery_example_celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  flower:
    image: fastapi_celery_example_celery_flower
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-flower.sh
    container_name: celery_flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: