"""Add non nullable address field to properties table

Revision ID: 1920bfcf0978
Revises: a87898744957
Create Date: 2023-09-16 12:52:27.456500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import model


# revision identifiers, used by Alembic.
revision: str = '1920bfcf0978'
down_revision: Union[str, None] = 'a87898744957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###
