"""Not nullable url

Revision ID: a87898744957
Revises: ad38a2ed5ade
Create Date: 2023-09-15 22:19:48.785221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import model


# revision identifiers, used by Alembic.
revision: str = 'a87898744957'
down_revision: Union[str, None] = 'ad38a2ed5ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapers', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrapers', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
