"""init

Revision ID: ad38a2ed5ade
Revises: 
Create Date: 2023-09-12 20:29:53.811875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import model
from sqlalchemy.dialects import postgresql

from sqlalchemy_utils import JSONType

from schema.pyandic_type import PydanticType
from schema.scraper import ScraperFilter

# revision identifiers, used by Alembic.
revision: str = 'ad38a2ed5ade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('scraper', sa.String(), nullable=True),
    sa.Column('filters', PydanticType(ScraperFilter), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('area', sa.Numeric(), nullable=False),
    sa.Column('available_on', sa.String(), nullable=True),
    sa.Column('rooms', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', JSONType(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('scrapers')
    # ### end Alembic commands ###
